#!/bin/bash

bindir=$(dirname $0)
repository="$1"
from="$2"
to="$3"

$bindir/process-path "$from" "$to" state $repository \
	$bindir/build_tcl \
		$bindir/build_ok build/tclsh \
			$bindir/save_and_bench ../tclbench
